service: serverless-python3-template

plugins:
  - serverless-offline
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8

custom:
  pythonRequirements:
    dockerizePip: false
    usePipenv: true

functions:
  hello:
    handler: functions/myip.handler
    events:
      - http:
          path: /my-ip
          method: get
